/* eslint-env node */
const SUCCESS_STATUS_CODE = 200;
const ERROR_STATUS_CODE = 400;
const SERVER_ERROR_CODE = 500;
const RESERVATION_STATES = ['PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED'];
const SPOT_TYPES = ['DESK', 'MEETINGROOM', 'PHONEBOOTH'];
const USER_ROLES = ['CLIENT', 'MANAGER'];
const TIME_SLOT_VALUES = ['MORNING', 'AFTERNOON', 'FULLDAY'];

module.exports = {
  SUCCESS_STATUS_CODE,
  ERROR_STATUS_CODE,
  SERVER_ERROR_CODE,
  RESERVATION_STATES,
  SPOT_TYPES,
  USER_ROLES,
  TIME_SLOT_VALUES,
};
